### ISSUE TITLE
Approve increments the allowance instead of setting it

### ISSUE THREAD

**Issue by jeisses** [neonexchange/neo-ico-template#11]
Hi all,

Thanks for providing this template, it's very helpful.

I noticed in [do_approve](https://github.com/neonexchange/neo-ico-template/blob/fef42840e197678b9ad66dcb91f272fd0d55fb4c/nex/token/nep5.py#L177), that the new approved value is added to the old approved value. I think that `do_approve` should *set* the value instead of incrementing it. NEP-5 states:

```
Remarks: "approve" will approve the to account to transfer amount tokens from the originator acount. 
```

Also in ERC20 it states that calling `approve` overwrites the value. Am I correct that this should be the behavior?

**Comment by nickfujita** [comment]
I am also curious about this. While running through `do_approve`, it seems that it also allows for negative amounts to be sent it. While this could be useful to adjusting the approval amount, it also allows for amounts to be set to negative. Reviewing it's usage in `do_transfer_from`, a negative amount stored by `do_approve` would not cause any problems since the correct checks are in place. However, it seems like it would be a waste to have a bunch of negative amounts being stored by `do_approve`.

So in addition to the suggestion above to set the value, could we also add a pre-check to ensure that the amount requested is greater than zero?

**Comment by brianlenz** [comment]
To add to what @nickfujita said, since `do_approve` is additive, the following check isn't all that useful:

```
if from_balance >= amount:
```

Say I have 100 NEP-5 tokens in my wallet. I could easily get around this check by doing multiple approvals of 100 tokens, effectively making this check meaningless.

Additionally, a common use case would be to clear an allowance (similar to the last scenario @nickfujita mentioned). If you want to clear an allowance, you have to first check the current balance, then do an approval of the negative version. This definitely all seems quite upside down. If an approve always does a replace, then you can just set it to 0 and be done.

I've created a PR with a proposal to address these issues, which should make it consistent with ERC20 standards.

**Comment by shargon** [comment]
This issue could be closed @localhuman

**Comment by localhuman** [comment]
closed via https://github.com/neonexchange/neo-ico-template/pull/14
